name: triva
description: "Mirac Altinay triva."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  retrofit: ^4.0.3
  pretty_dio_logger: ^1.1.1
  auto_route: ^10.0.1
  logger: ^2.0.2+1 #for logging purpose
  cached_network_image: ^3.2.3
  flutter_easyloading: ^3.0.5
  overlay_support: ^2.1.0
  cupertino_icons: ^1.0.2
  package_info_plus: ^8.3.0
  device_info_plus: ^9.1.1
  freezed: ^2.3.0 #code generator for unions/pattern-matching/copy
  json_serializable: ^6.5.4 #code generator for fromJson/toJson
  shared_preferences: ^2.2.2
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  get_it: ^7.6.4
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15

  flavor: ^2.0.0
  json_annotation: ^4.8.1
  retrofit_generator: ^9.2.0
  equatable: ^2.0.5
  flutter_lints: ^3.0.1
  flutter_secure_storage: ^9.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg







  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

