// File generated by FlutterFire CLI.
// This file should be added to your Flutter project
// You need to replace the placeholder values with actual values from your Firebase console

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can create these using the Firebase console.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can create these using the Firebase console.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can create these using the Firebase console.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can create these using the Firebase console.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATyClfz1LoMdTvgn6FHXDhOte28lyY0iE',
    appId: '1:956925446872:android:0aea2a847a1b54fd45e5ad',
    messagingSenderId: '956925446872',
    projectId: 'triva-66175',
    storageBucket: 'triva-66175.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8AS1vACvQ5V0xEcMJhExa_piSmjEn-vs',
    appId: '1:956925446872:ios:6f8fff0ef0b3979245e5ad',
    messagingSenderId: '956925446872',
    projectId: 'triva-66175',
    storageBucket: 'triva-66175.firebasestorage.app',
    iosBundleId: 'com.triva.app',
  );
}
